version: "3"

services:
  web:
    build: .
    image: hola-docker-2:1.0
    ports:
      - 5008:5008
    environment:
      MSG: ${MESSAGE}


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}