version: "3.8"

services:
  ui:
    container_name: ui
    image: yracnet/auth-ui:latest
    depends_on:
      - api-permiso
      - api-usuario
    ports:
      - "8080:80"
    volumes:
      - ./provider.json:/site/provider.json
    networks:
      - public

  api-permiso:
    container_name: api-permiso
    image: rimberth/auth-permiso:latest
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - JDBC_USER=${POSTGRES_USER}
      - JDBC_PASWD=${POSTGRES_PASSWORD}
    networks:
      - public
      - private

  api-usuario:
    container_name: api-usuario
    image: rimberth/auth-usuario:latest
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - JDBC_USER=${POSTGRES_USER}
      - JDBC_PASWD=${POSTGRES_PASSWORD}
    networks:
      - public
      - private

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - private

networks:
  public:
    driver: bridge
  private:

volumes:
  data:
    driver: local