# CONFIGURACION DEL PUERTO
server:
  port: 8081
  
# CONFIGURACION DEL DATASOURCE
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: '${JDBC_URL}'
    username: '${JDBC_USER}'
    password: '${JDBC_PASWD}'
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    jdbc:
      repositories:
        enabled: false