CREATE TABLE usuario(ID INT PRIMARY KEY NOT NULL, 
NOMBRES TEXT NOT NULL, 
APELLIDOS TEXT NOT NULL, 
EMAIL TEXT NOT NULL, 
DESCRIPCION TEXT NOT NULL);

CREATE TABLE permiso(
ID INT PRIMARY KEY NOT NULL,
USUARIOID INT NULL, 
PERMITIDO BOOLEAN NULL, 
MODULO TEXT NULL);

ALTER TABLE ONLY public.permiso
    ADD CONSTRAINT FK_PERMISO_USUARIO FOREIGN KEY (ID) REFERENCES public.usuario(ID) NOT VALID;